name: KBOT-CI/CD Pipeline

on: 
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  TARGETOS: linux
  TARGETARCH: amd64

jobs:
    ci:
      name: CI
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            fetch-depth: 0

        - name: Set up Go
          uses: actions/setup-go@v3
          with:
            go-version: '1.24'
            cache: true

        - name: Run golangci-lint
          uses: golangci/golangci-lint-action@v3
          with:
            version: latest
            args: --timeout=5m

        # - name: Run test
        #   run: make test

    cd:
      name: CD
      needs: ci
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            fetch-depth: 0

        - name: Set up Go
          uses: actions/setup-go@v3
          with:
            go-version: '1.24'
            cache: true

        - name: Set version
          # run: echo "VERSION=$(git describe --tags --abbrev=0)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          run: |
            VERSION=$(git describe --tags --abbrev=0)-$(git rev-parse --short HEAD)
            echo "VERSION=$VERSION" >> $GITHUB_ENV
            echo "Using version: $VERSION"

        # - name: Docker Hub login
        #   uses: docker/login-action@v2
        #   with:
        #     username: ${{ secrets.DOCKERHUB_USERNAME }}
        #     password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build and push Docker image
          env:
            APP: "kbot"
            REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}
          run: |
            make image push \
              TARGETARCH=${{ env.TARGETARCH }} \
              TARGETOS=${{ env.TARGETOS }} \
              VERSION=${{ env.VERSION }}

        - name: Update Helm chart
          uses: mikefarah/yq@master
          with:
            cmd: yq -i '.image.tag=strenv(VERSION) | .image.arch=strenv(TARGETARCH)' helm/values.yaml
        - run: |
            git config user.name github-actions
            git config user.email github-actions@github.com
            git commit -am "update version $VERSION"
            git push

        - name: Cleanup
          run: make clean TARGETARCH=${{ env.TARGETARCH }}
